export const ALLOC_COLORS = ["#2563eb", "#3fb950", "#f59e0b", "#f85149", "#38bdf8", "#a78bfa"];

export const portfolioStyles = {
  root: { display: "flex", flexDirection: "column", gap: 16 },
  summaryGrid: { display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: 10 },
  summaryCard: { borderRadius: 10, border: "1px solid var(--border-card)", background: "var(--bg-card)", padding: "16px 18px" },
  summaryLabel: { fontSize: 12, color: "var(--text-muted)", marginBottom: 8 },
  summaryValue: { fontSize: 22, fontWeight: 700 },
  summarySub: { fontSize: 11, color: "var(--text-muted)", marginTop: 4 },
  errBox: { borderRadius: 8, border: "1px solid var(--danger-border)", background: "var(--danger-bg)", color: "var(--danger-text)", padding: "10px 14px", fontSize: 13 },
  chartsRow: { display: "grid", gridTemplateColumns: "1fr 300px", gap: 12 },
  chartCard: { borderRadius: 10, border: "1px solid var(--border-card)", background: "var(--bg-card)", padding: "16px 18px", display: "flex", flexDirection: "column" },
  chartBody: { flex: 1, display: "flex", flexDirection: "column", justifyContent: "center" },
  allocCard: { borderRadius: 10, border: "1px solid var(--border-card)", background: "var(--bg-card)", padding: "16px 18px" },
  chartTitle: { fontSize: 14, fontWeight: 600, color: "var(--text-primary)", marginBottom: 2 },
  chartSub: { fontSize: 12, color: "var(--text-muted)", marginBottom: 12 },
  legendGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: "4px 10px", marginTop: 8 },
  legendItem: { display: "flex", alignItems: "center", gap: 6 },
  legendDot: { width: 8, height: 8, borderRadius: "50%", flexShrink: 0 },
  legendName: { fontSize: 11, color: "var(--text-muted)", flex: 1 },
  legendPct: { fontSize: 11, fontWeight: 600, color: "var(--text-primary)" },

  // Portfolio Allocation card — enriched layout
  allocTotalRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "baseline",
    padding: "10px 12px",
    background: "var(--bg-panel)",
    border: "1px solid var(--border-card)",
    borderRadius: 8,
    marginBottom: 8,
  },
  allocTotalLabel: {
    fontSize: 11,
    color: "var(--text-muted)",
    textTransform: "uppercase",
    letterSpacing: 0.4,
    fontWeight: 600,
  },
  allocTotalValue: {
    fontSize: 16,
    fontWeight: 700,
    color: "var(--text-primary)",
    fontVariantNumeric: "tabular-nums",
  },
  allocCenter: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    textAlign: "center",
    pointerEvents: "none",
  },
  allocCenterPct: {
    fontSize: 22,
    fontWeight: 800,
    color: "var(--text-primary)",
    letterSpacing: "-0.02em",
  },
  allocCenterLabel: {
    fontSize: 11,
    color: "var(--text-muted)",
    marginTop: 2,
    maxWidth: 90,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  allocLegendList: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    marginTop: 10,
  },
  allocLegendRow: {
    display: "grid",
    gridTemplateColumns: "10px minmax(0, 1fr) auto auto",
    alignItems: "center",
    gap: 8,
    padding: "4px 0",
    fontVariantNumeric: "tabular-nums",
  },
  allocLegendName: {
    fontSize: 12,
    color: "var(--text-primary)",
    fontWeight: 500,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  allocLegendValue: {
    fontSize: 11,
    color: "var(--text-muted)",
  },
  allocLegendPct: {
    fontSize: 12,
    color: "var(--text-primary)",
    fontWeight: 700,
    minWidth: 48,
    textAlign: "right",
  },
  holdingsCard: { borderRadius: 10, border: "1px solid var(--border-card)", background: "var(--bg-card)", padding: "16px 18px" },
  holdingsHeader: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 14 },
  tableWrap: { overflowX: "auto" },
  table: { width: "100%", borderCollapse: "collapse" },
  th: { textAlign: "left", padding: "8px 12px", fontSize: 11, fontWeight: 600, color: "var(--text-muted)", borderBottom: "1px solid var(--border)", whiteSpace: "nowrap" },
  tr: { borderBottom: "1px solid var(--border-soft)" },
  td: { padding: "10px 12px", fontSize: 13, color: "var(--text-primary)", whiteSpace: "nowrap" },
  symbolBadge: { padding: "2px 8px", borderRadius: 4, background: "rgba(37,99,235,0.15)", border: "1px solid var(--accent-border)", fontSize: 12, fontWeight: 600 },
  empty: { color: "var(--text-muted)", fontSize: 13, padding: "20px 0", textAlign: "center" },
  emptyBox: { borderRadius: 8, border: "1px dashed var(--border-card)", padding: "24px", textAlign: "center" },
  addBtn: { padding: "8px 16px", borderRadius: 8, border: "none", background: "var(--accent-solid)", color: "#fff", cursor: "pointer", fontWeight: 600, fontSize: 13 },
  sellBtn: { padding: "6px 12px", borderRadius: 6, border: "1px solid var(--danger-border)", background: "var(--danger-bg)", color: "var(--danger-text)", cursor: "pointer", fontSize: 12, fontWeight: 500 },
  ghostBtn: { padding: "8px 16px", borderRadius: 8, border: "1px solid var(--border-card)", background: "transparent", color: "var(--text-primary)", cursor: "pointer" },
  primaryBtn: { padding: "8px 16px", borderRadius: 8, border: "none", background: "var(--accent-solid)", color: "#fff", cursor: "pointer", fontWeight: 600 },
  formGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 },
  label: { fontSize: 12, color: "var(--text-muted)" },
  input: { padding: "9px 12px", borderRadius: 8, border: "1px solid var(--input-border)", background: "var(--input-bg)", color: "var(--text-primary)", outline: "none", width: "100%", boxSizing: "border-box" },
  dropdown: { position: "absolute", top: "100%", left: 0, right: 0, zIndex: 100, background: "var(--dropdown-bg)", border: "1px solid var(--border-card)", borderRadius: 8, marginTop: 4, overflow: "hidden" },
  dropdownItem: { display: "flex", alignItems: "center", padding: "9px 12px", cursor: "pointer", fontSize: 13, borderBottom: "1px solid var(--border-soft)", color: "var(--text-primary)" },
  infoBox: { borderRadius: 8, border: "1px solid var(--border-card)", background: "var(--bg-panel)", padding: "10px 12px", display: "grid", gap: 8 },
  warnBox: { borderRadius: 6, border: "1px solid rgba(245,158,11,0.35)", background: "rgba(245,158,11,0.10)", color: "#fbbf24", padding: "8px 12px", fontSize: 12 },
  periodBtn: {
    padding: "6px 12px",
    borderRadius: 6,
    border: "1px solid var(--border-card)",
    background: "transparent",
    color: "var(--text-muted)",
    cursor: "pointer",
    fontSize: 11,
    fontWeight: 600,
    transition: "all 0.2s",
  },
  periodBtnActive: {
    border: "1px solid #3b82f6",
    background: "rgba(59, 130, 246, 0.15)",
    color: "#3b82f6",
  },
  allocViewBtn: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 7,
    borderRadius: 6,
    border: "1px solid var(--border-card)",
    background: "transparent",
    color: "var(--text-muted)",
    cursor: "pointer",
    transition: "all 0.2s",
  },
  allocViewBtnActive: {
    border: "1px solid var(--accent-solid)",
    background: "var(--accent)",
    color: "var(--accent-solid)",
  },
};
