[SERVICE]
    Flush        5
    Daemon       Off
    Log_Level    info
    Parsers_File parsers.conf

[INPUT]
    Name              tail
    Path              /app/logs/application.json
    Parser            json
    Tag               finans.backend
    Refresh_Interval  5
    Mem_Buf_Limit     5MB
    Skip_Long_Lines   On

[FILTER]
    Name    modify
    Match   finans.*
    Add     service finans-backend
    Add     environment dev

[OUTPUT]
    Name            opensearch
    Match           finans.*
    Host            opensearch
    Port            9200
    Index           finans-portal-logs
    Type            _doc
    Suppress_Type_Name On
    Logstash_Format On
    Logstash_Prefix finans-portal-logs
    Logstash_DateFormat %Y.%m.%d
    Retry_Limit     5
    tls             Off
    tls.verify      Off

[OUTPUT]
    Name   stdout
    Match  finans.*
    Format json_lines
