spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/finans
    username: finans
    password: finans
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
